### ISSUE TITLE
doesn't decrypt

### ISSUE THREAD

**Issue by moosje2003** [0xdeb7ef/spass-manager#1]
everything is still encrypted

**Comment by moosje2003** [comment]
And file is to big for chrome to import

**Comment by 0xdeb7ef** [comment]
The passwords themselves are base64 encoded, I will have to add a step to "sanitize" the output.

**Comment by 0xdeb7ef** [comment]
@moosje2003 I've added a `-format` flag that currently supports `chrome`.

**Comment by moosje2003** [comment]
> @moosje2003 I've added a `-format` flag that currently supports `chrome`.

how do i use that
